name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access
# Stolen from https://github.com/Critical-Impact/InventoryTools/blob/main/.github/workflows/build.yml

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  INTERNAL_NAME: AdaptiveHud
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Restore
        run: dotnet restore AdaptiveHud
      - name: Build
        run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore ${{ env.INTERNAL_NAME }}
      - name: Push artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            AdaptiveHud\bin\Release\